/* Reproducible editable PowerPoint generation. No source workbook is opened or changed. */
const fs=require('fs'), path=require('path');
const runtime=process.env.CODEX_NODE_MODULES||'C:/Users/Nevo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const pptxgen=require(path.join(runtime,'pptxgenjs'));
const sharp=require(path.join(runtime,'sharp'));
const A=path.resolve(__dirname,'..'), C=path.join(A,'content');
const source=JSON.parse(fs.readFileSync(path.join(C,'source-material.json'),'utf8'));
for(const a of source.articles){for(const block of a.references||[]){for(const para of block.text.split(/\n\s*\n/)){let u=para.match(/https?:\/\/[^\s<>]+/);if(u){let url=u[0].replace(/[.,;]+$/,'');if(!a.links.some(x=>x.url===url))a.links.push({title:para.replace(/^\[\d+\]\s*/,'').split(/https?:/)[0].replace(/[.,;\s]+$/,'').slice(0,150),url,date:(para.match(/\b(?:19|20)\d{2}\b/)||[])[0]});}}}}
const content=fs.readdirSync(C).filter(x=>x.endsWith('.json')&&!['source-material.json','episode-manifest.json'].includes(x)).flatMap(x=>{let j=JSON.parse(fs.readFileSync(path.join(C,x),'utf8'));return Array.isArray(j)?j:[]});
const selected=process.argv.slice(2), out=path.join(A,'Decks');
const COLORS={navy:'163047',teal:'176F73',gold:'BB8432',paper:'F7F5EF',muted:'50616B',line:'D7DEDB',white:'FFFFFF',pale:'E9EFE7'};
const WEBMAP={'AMBC-02':'business-credit','IIDF-01':'global-funding','IIDF-03':'global-funding','KTHF-02':'lab','KTHF-04':'mortgage','KECA-02':'dcf-value','KECA-03':'dca-portfolio','KECA-04':'lab','NSE-DG-01':'dca-dividend','NSE-DG-02':'dca-portfolio','USMPC-02':'global-funding','USMPC-03':'global-funding','USMPC-04':'dca-portfolio','USMPC-05':'dca-portfolio','USMPC-06':'dca-portfolio','USMPC-08':'dca-portfolio','USMPC-09':'lab','OE-MSME-01':'owner-earnings','OE-MSME-02':'owner-earnings','OE-MSME-03':'cash-13-weeks','OE-MSME-04':'cash-13-weeks','OE-MSME-05':'owner-earnings','OE-VALUATION-06':'dcf-value','OE-VALUATION-07':'dcf-value','OE-VALUATION-08':'dcf-value','OE-FAILURE-11':'failure-warning','OE-FAILURE-12':'failure-warning','OE-FAILURE-13':'failure-warning'};
let web=JSON.parse(fs.readFileSync(path.join(A,'Evidence/Web/capture-manifest.json'),'utf8')).map(x=>({...x,base:'Evidence/Web'}));
const extra=path.join(A,'Evidence/Web/20260925-formula-rendering/manifest.json');
if(fs.existsSync(extra)) {let e=JSON.parse(fs.readFileSync(extra,'utf8'));if(!Array.isArray(e))e=e.captures||e.tools||e.pages||[];web.push(...e.map(x=>({...x,slug:x.slug||(x.key==='credit-detailed'?'business-credit':x.key),screenshots:x.screenshots||x.files,environment:'local preview; not proof of live deployment',base:'Evidence/Web/20260925-formula-rendering'})));}
const manifest=[];
function clean(x){return String(x||'').replace(/\*\*/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/\\(?:\[|\])/g,'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'');}
function txt(s,text,x,y,w,h,size=22,opts={}) {s.addText(clean(text),{x,y,w,h,fontFace:'Aptos',fontSize:size,color:COLORS.navy,breakLine:false,margin:0,paraSpaceAfter:6,valign:'top',...opts});}
function rect(s,x,y,w,h,color,opts={}) {s.addShape('rect',{x,y,w,h,line:{color,transparency:100},fill:{color},...opts});}
function footer(s,a,n,label){txt(s,'SOKOINTEL  /  '+a.id,0.55,7.08,3.1,.19,9,{color:COLORS.muted,charSpacing:1});txt(s,label||'Source material and recording notes included',3.55,7.08,8.35,.19,9,{color:COLORS.muted});txt(s,String(n).padStart(2,'0'),12.08,7.06,.65,.23,10,{align:'right',color:COLORS.teal});}
function notes(s,a,text){text=text.replaceAll('Trade_i=w_i^V-V_i','Trade_i = target weight_i × total portfolio value − current sleeve value_i [multiplication notation clarified from the source extraction]');s.addNotes(`EPISODE ${a.id}: ${a.title}\nARTICLE: https://sokointel.com/read/${a.slug}/\nRESEARCH SNAPSHOT: ${source.research_date||'Source-specific dated material; see references'}\n\n${text}\n\nPresentation assembled 25 September 2026. Educational source snapshot; no recording or publication is implied.`);}
function base(p,a,title,kicker){let s=p.addSlide();s.background={color:COLORS.paper};rect(s,0,0,13.333,.11,COLORS.teal);txt(s,kicker||a.id,.55,.4,12.2,.25,11,{color:COLORS.teal,bold:true,charSpacing:1.5});txt(s,title,.55,.94,12.2,1.03,title.length>45?29:34,{fontFace:'Georgia'});footer(s,a,p._slides.length);return s;}
function noteLabel(s,label,y=6.62){txt(s,label,.65,y,12,.3,10,{color:COLORS.muted});}
function addPoint(s,text,index,x,y,w){rect(s,x,y,.08,.83,COLORS.teal);txt(s,String(index+1).padStart(2,'0'),x+.2,y,.55,.35,13,{color:COLORS.gold,bold:true});txt(s,text,x+.85,y,w-.85,1.15,text.length>205?19:22);}
function sourceExcerpt(a,title){let tokens=title.toLowerCase().match(/[a-z]{4,}/g)||[];let ranked=a.sections.filter(s=>!/^References/.test(s.heading)).map(s=>({s,score:tokens.reduce((v,t)=>v+(s.heading.toLowerCase().includes(t)?5:0)+(s.text.toLowerCase().includes(t)?1:0),0)})).sort((x,y)=>y.score-x.score);return ranked.slice(0,2).map(x=>`ARTICLE SECTION: ${x.s.heading}\n${x.s.text.slice(0,3500)}`).join('\n\n');}
async function imageContain(s,file,x,y,w,h){let m=await sharp(file).metadata();let scale=Math.min(w/m.width,h/m.height);s.addImage({path:file,x:x+(w-m.width*scale)/2,y:y+(h-m.height*scale)/2,w:m.width*scale,h:m.height*scale});}
function sourcesFor(a,d){let arr=d.sources?.length?d.sources:a.links.filter(x=>!/^\d+$/.test(x.title)&&!/^\[/.test(x.title));if(!arr.length)arr=a.links;if(!arr.length){arr=[{title:'Source article: '+a.title,url:`https://sokointel.com/read/${a.slug}/`},...Array.from(new Set(a.evidence.map(x=>path.basename(x.workbook)))).map(x=>({title:'Companion workbook: '+x.replace(/\.xlsx$/i,'')})),{title:'Exact source ranges: '+a.evidence.map(x=>`'${x.sheet}'!${x.range}`).join('; ')},{title:'Source dates and assumptions: retain the period labels in the article and captured workbook; full provenance in notes.'}];}return arr.slice(0,4);}
async function make(a,d){
 let p=new pptxgen();p.layout='LAYOUT_WIDE';p.author='Sokointel';p.subject=a.questions?.join(' | ')||a.title;p.title=a.title;p.company='Sokointel';p.lang='en-GB';p.theme={headFontFace:'Georgia',bodyFontFace:'Aptos',lang:'en-GB'};
 let records=[];const keep=(type,title,evidence)=>records.push({number:p._slides.length,type,title,evidence});
 let s=p.addSlide();s.background={color:COLORS.navy};rect(s,0,0,.16,7.5,COLORS.gold);txt(s,'SOKOINTEL  /  RESEARCH EXPLAINED',.75,.58,11.8,.3,13,{color:'B9DAD6',charSpacing:2});txt(s,a.title,.75,1.5,11.8,2.1,a.title.length>75?36:42,{fontFace:'Georgia',color:COLORS.white});txt(s,d.case,.78,4.03,10.8,1.35,24,{color:'E3ECE8'});txt(s,a.id+'   •   '+d.caseLabel,.78,6.53,11.8,.46,12,{color:'B9DAD6'});notes(s,a,`OPENING NARRATION\n${d.case}\n${d.caseLabel}\nIntroduce the decision before defining the technical terms.\n${sourceExcerpt(a,'Opening')}`);keep('opening',a.title);
 s=base(p,a,'The questions and the language','THE DECISION');
 let qs=(a.questions||[]).slice(0,4);if(qs.length>3){qs.forEach((q,i)=>txt(s,`${i+1}. ${q}`,.65,2.02+i*1.13,6.45,1.03,20,{paraSpaceAfter:0}));}else{txt(s,qs.map((q,i)=>`${i+1}. ${q}`).join('\n\n'),.65,2.02,6.45,4.55,qs.join('').length>500?20:21);}rect(s,7.51,1.98,5.17,4.76,COLORS.pale);txt(s,'TERMS & UNITS',7.78,2.23,4.61,.3,12,{color:COLORS.teal,bold:true});d.units.slice(0,5).forEach((u,i)=>txt(s,u,7.78,2.82+i*.72,4.57,.66,16.5,{paraSpaceAfter:0}));notes(s,a,`Read the questions naturally and define terms in context.\n${d.units.join('\n')}\nResearch question mapping: ${a.storyboard?.[1]?.['Research questions']||a.questions?.join('; ')}`);keep('questions-and-glossary','The questions and the language');
 for(let b of d.beats.slice(0,3)){s=base(p,a,b.title,'FOLLOW THE MECHANISM');b.points.slice(0,3).forEach((x,i)=>addPoint(s,x,i,.72,2.04+i*1.39,11.7));noteLabel(s,d.caseLabel);notes(s,a,`${b.notes||''}\n\nNarration: explain each step and its consequence for the opening decision.\n\n${sourceExcerpt(a,b.title+' '+b.points.join(' '))}`);keep('explanation',b.title);}
 let f=d.calculation;s=base(p,a,f.title,'THE RELATIONSHIP');rect(s,.65,2.02,12.0,1.16,COLORS.pale);txt(s,f.equation,.95,2.20,11.4,.85,f.equation.length>55?24:28,{fontFace:'Cambria Math',align:'center',color:COLORS.teal});txt(s,f.substitution,.85,3.6,11.7,1.18,25,{bold:true});txt(s,f.interpretation,.85,5.09,11.65,1.18,23);noteLabel(s,d.caseLabel);notes(s,a,`${f.notes||''}\nEquation: ${f.equation}\nSubstitution: ${f.substitution}\nInterpretation: ${f.interpretation}\n\n${sourceExcerpt(a,f.title)}`);keep('calculation',f.title);
 for(let [i,e] of a.evidence.slice(0,2).entries()){s=base(p,a,`${e.sheet}: follow the saved workbook`,'WORKBOOK EVIDENCE');rect(s,.55,1.94,12.23,4.2,COLORS.white);await imageContain(s,path.join(A,e.images[0]),.67,2.05,12.0,3.98);txt(s,`${e.sheet}!${e.range}`,.67,6.31,10.2,.35,18,{bold:true,color:COLORS.teal});noteLabel(s,e.bridge?'Companion teaching bridge from another series; not a reconstruction of this article’s case.':d.caseLabel,6.72);notes(s,a,`ACTUAL WORKBOOK CAPTURE\nWorkbook: ${e.workbook}\nSheet/range: '${e.sheet}'!${e.range}\nSHA-256: ${e.sha256}\nCapture method: ${e.method}\nAsset: ${e.images[0]}\n${e.bridge?'This capture is explicitly a cross-series teaching bridge. Its figures are not the article case.':''}\n\nSCREEN RECORDING WALKTHROUGH\nRead the row and column headings. Identify inputs, follow the dependent row and explain the units. Do not alter the source workbook while recording; use a copy for a new scenario.\n\nExtracted evidence text:\n${e.pdf_text}\n\nRelevant article context:\n${sourceExcerpt(a,e.sheet)}`);keep('workbook-evidence',e.sheet,{...e,pdf_text:undefined,cells:undefined});}
 let sc=d.scenario;s=base(p,a,sc.title,'CHANGE THE ASSUMPTION');rect(s,.65,2.06,5.82,2.16,COLORS.pale);rect(s,6.77,2.06,5.82,2.16,'EFE6D5');txt(s,'BASE / STARTING RECORD',.95,2.34,5.2,.25,12,{bold:true,color:COLORS.teal});txt(s,sc.baseline,.95,2.87,5.2,1.1,22);txt(s,'CHANGED CASE / NEW EVIDENCE',7.07,2.34,5.2,.25,12,{bold:true,color:'80591D'});txt(s,sc.changed,7.07,2.87,5.2,1.1,22);txt(s,sc.consequence,.82,4.79,11.72,1.39,25);noteLabel(s,'Sensitivity or evidence comparison; interpretation depends on the stated assumptions.');notes(s,a,`${sc.notes||''}\nBase: ${sc.baseline}\nChanged: ${sc.changed}\nConsequence: ${sc.consequence}\n\n${sourceExcerpt(a,sc.title)}`);keep('scenario',sc.title);
 const slug=WEBMAP[a.id];let w=web.filter(x=>x.slug===slug).at(-1);
 if(w){let images=w.screenshots||[];let pic=images.find(x=>typeof x==='string'&&/summary/.test(x))||images.find(x=>typeof x==='string'&&/results/.test(x))||images.find(x=>typeof x==='string');
  if(slug==='dca-dividend')pic='dca-dividend-table-crop.png';
  if(pic){let file=path.isAbsolute(pic)?pic:path.join(A,w.base,pic);if(fs.existsSync(file)){
   let copy={
    'dca-dividend':['Follow capital, cost reserve, target allocation and whole-share quantity in the saved table. Recalculate after a changed price or dividend assumption.','Income KES 1,015.51 / KES 100,000 = 1.02%. Captured page yield formatting is under review.'],
    'dca-portfolio':['Use target weights, reference prices and costs to form an affordable purchase plan. Follow the residual cash after integer-share rounding.','Stress losses, covariance and HHI belong in the workbook, not this purchase planner.'],
    'lab':['Compare a lump sum and scheduled contributions under a constant annual return. Inspect beginning versus end-of-period payment timing.','Return sequences, withdrawals and stochastic pension paths require the workbook.'],
    'global-funding':['Compare funding and FX charges for the same amount and route. Check the customer, account ownership and currency assumptions.','Fund domicile, residence and tax treatment require the separate article record.'],
    'dcf-value':['Use five-year FCFF, a matching WACC and terminal growth. Inspect the forecast and terminal dependence before changing the discount rate.','This separate default is not an issuer valuation. After-interest owner earnings is not FCFF.'],
    'owner-earnings':['Trace the annual earnings bridge and the separate dated cash test. A proposed draw changes headroom without changing annual earning power.','Reconcile the selected article case; do not mix it with the larger general workbook example.'],
    'cash-13-weeks':['Follow the lowest cash week and final balance. Distinguish customer receipts from financing and disclose receipts delayed beyond week thirteen.','This is a fictional schedule. Weekly totals do not prove every payment clears within the week.'],
    'failure-warning':['Inspect a separate fictional weekly stress plan. Pull supplier payments forward or delay receipts, then identify the first reserve and cash breach.','The stress schedule is not the cash record of a named company or a probability of failure.'],
    'business-credit':['Follow net advance, interest, fees and dated repayment. Delay the customer collection while retaining the contractual due date.','An explicitly extended facility is a separate contract scenario; no automatic rollover is assumed.'],
    'mortgage':['Inspect payment, interest, principal and final balance. Compare a rate assumption or extra payment while preserving the remaining loan term.','The calculator default is separate from the article household and its full rent-versus-buy model.']
   }[slug]||['Inspect inputs, units and the displayed result.','Reconcile the calculator default with the article case before comparing.'];
   s=base(p,a,'A focused calculator demonstration',w.environment?'LOCAL PREVIEW CAPTURE':'SAVED WEB DEMONSTRATION');await imageContain(s,file,.65,1.98,8.07,4.74);rect(s,9.05,2.04,3.6,4.55,COLORS.pale);txt(s,'WHAT THIS TOOL DOES',9.31,2.31,3.06,.3,12,{bold:true,color:COLORS.teal});txt(s,copy[0],9.31,2.88,3.06,2.02,19);txt(s,copy[1],9.31,5.05,3.06,1.3,16.5,{bold:true});
   noteLabel(s,`${w.environment?'Local preview':'Saved production page'} • ${new URL(w.url).pathname} • captured ${(w.captured_at||'2026-09-25').slice(0,10)}`,6.78);
   notes(s,a,`REAL WEB CAPTURE\n${JSON.stringify(w,null,2)}\n\nDEMONSTRATION SCOPE\n${copy.join('\n')}\n\nThe calculator defaults may be a separate teaching example. Do not claim the displayed default equals the article or workbook case unless inputs and conventions have been reconciled. DCF uses FCFF discounted at WACC, subtracting net debt once; do not put after-interest owner earnings into that model. For financial companies use the separate capital model.\nFor the DCA dividend capture only: the original page renders a fraction as a percentage without multiplying by 100. The derived screenshot is an exact table crop excluding that card, not a retouched page. Correct yield = 1,015.5093/100,000 ×100 = 1.0155093%, approximately 1.02%. The protected tool was not changed.\nThe DCA portfolio calculator is limited to purchase/allocation mechanics and does not calculate a 30-company HHI, correlation or a stress loss. The compounding explorer is a constant-return contribution-timing model, not a sequence-of-returns withdrawal simulation.`);
   keep('web-evidence',slug,{url:w.url,captured_at:w.captured_at,environment:w.environment||'saved production page',path:path.relative(A,file).replaceAll('\\','/'),inputs:w.inputs,scope:copy});
  }}
 }
 s=base(p,a,'What the evidence lets us conclude','ANSWER THE OPENING QUESTION');txt(s,d.answer,.78,2.03,11.77,2.04,27);rect(s,.67,4.47,11.99,2.19,COLORS.pale);txt(s,'YOUR NEXT RECORD',.96,4.76,11.3,.28,12,{bold:true,color:COLORS.teal});txt(s,d.action,.96,5.25,11.25,1.20,23);notes(s,a,`Answer: ${d.answer}\nViewer task: ${d.action}\nReturn to each opening research question and identify what remains conditional or unknown.\n${sourceExcerpt(a,'implementation review decision')}`);keep('conclusion','What the evidence lets us conclude');
 s=base(p,a,'Sources, dates and companion material','SOURCE RECORD');txt(s,`Read the episode: sokointel.com/read/${a.slug}/`,.72,2.02,11.9,.6,23,{color:COLORS.teal,hyperlink:{url:`https://sokointel.com/read/${a.slug}/`}});let refs=sourcesFor(a,d);refs.forEach((r,i)=>{txt(s,`${i+1}. ${clean(r.title).slice(0,125)}${r.date?' • '+r.date:''}`,.76,2.95+i*.63,11.85,.52,17,{color:COLORS.navy,hyperlink:r.url?{url:r.url}:undefined});});txt(s,'Full source references, workbook paths, cell ranges and capture metadata are preserved in speaker notes and the episode manifest.',.76,5.82,11.8,.78,18,{color:COLORS.muted});notes(s,a,`SOURCE MATERIAL\n${a.references.map(x=>x.text).join('\n\n')}\n\nAll linked source URLs:\n${a.links.map(x=>`${x.title}: ${x.url}`).join('\n')}\n\nAdditional content sources:\n${JSON.stringify(d.sources||[],null,2)}\n\nWorkbook provenance:\n${a.evidence.map(e=>`${e.workbook}\n'${e.sheet}'!${e.range}\n${e.sha256}`).join('\n\n')}\n\nArticle catalog snapshot hash: ${source.source_catalog_sha256}`);keep('sources','Sources, dates and companion material');
 let folder=path.join(out,a.series_id);fs.mkdirSync(folder,{recursive:true});let file=path.join(folder,a.id+'.pptx');await p.writeFile({fileName:file});let result={article_id:a.id,series_id:a.series_id,title:a.title,article_url:`https://sokointel.com/read/${a.slug}/`,slides:records.length,path:path.relative(A,file).replaceAll('\\','/'),status:'editable_pptx_built',recording_status:'not_recorded',publishing_status:'not_published',source_catalog_sha256:source.source_catalog_sha256,sources:a.links,workbook_sources:a.evidence.map(e=>({workbook:e.workbook,sheet:e.sheet,range:e.range,sha256:e.sha256,method:e.method,bridge:e.bridge})),screenshots:records.filter(x=>x.evidence).map(x=>x.evidence),slide_plan:records,qa:{structural:'pending',visual:'pending',notes:'every slide contains recording and source notes',native_editable_text:true}};manifest.push(result);console.log(`${a.id}: ${records.length} slides → ${file}`);
}
(async()=>{for(let d of content){let a=source.articles.find(x=>x.id===d.id);if(a&&(!selected.length||selected.includes(d.id)))await make(a,d);}let dest=path.join(A,'episode-manifest.json');let old=fs.existsSync(dest)?JSON.parse(fs.readFileSync(dest,'utf8')).episodes:[];let merged=[...old.filter(x=>!manifest.some(m=>m.article_id===x.article_id)),...manifest].sort((a,b)=>source.articles.findIndex(x=>x.id===a.article_id)-source.articles.findIndex(x=>x.id===b.article_id));fs.writeFileSync(dest,JSON.stringify({generated_at:new Date().toISOString(),research_catalog_date:source.research_date,expected_episodes:41,deck_count:merged.length,total_slides:merged.reduce((v,x)=>v+x.slides,0),episodes:merged},null,2));})();
