"""Episode-specific narrative selections from the approved article/storyboard corpus."""
from pathlib import Path
import json
A=Path(__file__).resolve().parents[1]
src=json.loads((A/'content/source-material.json').read_text(encoding='utf-8'))
def F(title,eq,sub,meaning,notes='Article worked example and saved workbook evidence; preserve their separate assumptions.'):
 return dict(title=title,equation=eq,substitution=sub,interpretation=meaning,notes=notes)
def S(title,base,changed,result,notes='Teaching sensitivity; hold other assumptions fixed unless a multi-input case is explicitly named.'):
 return dict(title=title,baseline=base,changed=changed,consequence=result,notes=notes)
def B(title,*points): return dict(title=title,points=list(points),notes='Explain the mechanism with the cited article section, then relate it to the opening decision.')
D={
'AMBC-01':dict(units=['FDI — investment flow for a defined period','Capital released — cash no longer tied up; KES','Financing rate — annual cost assumption; %','Currency quote — KES per USD'],calculation=F('Reliability can release operating cash','Cash released = current cycle cash − improved cycle cash','KES 5.0m − KES 4.0m = KES 1.0m; × 18% = KES 180,000/year','Released cash can reduce financing needs; it is not new accounting profit.'),scenario=S('A weaker improvement releases less cash','KES 5m current cycle → KES 4m improved cycle.','Only improve to KES 4.5m; keep 18% financing cost.','Cash released falls to KES 500,000; simple annual financing cost avoided falls to KES 90,000.'),action='Cost one identifiable regional order: buyer, delivery, supplier payments, customer collection date and contingency.'),
'AMBC-02':dict(units=['Principal — amount advanced before fees; KES','Tenor — days from draw to repayment','Actual/365 — annual rate applied to actual elapsed days','Annual cash-flow yield — rate based on net advance and dated repayments'],calculation=F('Price the complete facility','Finance cost = principal × annual rate × days/365 + fees','KES 520,000 × 18% × 30/365 + KES 10,400 = KES 18,093.15','Order contribution after finance is KES 261,906.85 under the source assumptions.','P2 Facility B7:E14. Fees are 2% of original principal. The web draw date translates workbook day 15 to day zero.'),scenario=S('Late collection is not an automatic loan extension','30-day contract; customer pays on the expected collection date.','Delay collection by 14 days while retaining the original repayment date.','Web repayment-date gap: KES 538,093.15. An explicitly revised 44-day loan instead costs KES 21,683.29.','The workbook late row extends finance to 44 days. The web delayed-receipt case holds the contract fixed. Explain the different assumptions; do not conflate the two.'),action='Reconcile account credits into trading receipts, financing, transfers and unresolved items before using them as repayment evidence.'),
'IIDF-01':dict(units=['S₀, S₁ — starting/ending exchange rate; KES/USD','R — investment return in USD; decimal','Domicile — legal home of the fund','Trading currency — currency of the quotation, not the full economic exposure'],calculation=F('Translate both the asset and the currency','KES return = (1 + R) × (S₁ ÷ S₀) − 1','1.08 × (120 ÷ 130) − 1 = −0.3077%','USD 10,000 grows to USD 10,800, but its KES value falls from 1.300m to 1.296m.','Article worked calculation 2. All inputs hypothetical. The USMPC workbook withholding screen is a separate companion example.'),scenario=S('Hold the USD return; change only the exchange rate','8% USD gain; 130 → 120 KES/USD produces −0.3077% in KES.','Change ending exchange rate to 145 KES/USD.','Ending value becomes KES 1.566m; the KES return becomes 20.4615%. Neither exchange-rate path is a forecast.'),action='Complete a five-identity fund record: exposure, domicile, share class, trading currency and exchange.'),
'IIDF-02':dict(units=['ERI — excess reported income; income without necessarily receiving cash','Residence — jurisdiction-specific legal tests, followed by treaty analysis where relevant','Cost basis — allowable acquisition cost in reporting currency','Tax year — preserve the recognition date and currency'],calculation=F('Track income before calculating the later gain','ERI = units × ERI per unit','1,000 × GBP 0.80 = GBP 800; later gain = 12,000 − 10,000 − 800 = GBP 1,200','The GBP 800 income and GBP 1,200 disposal gain may arise in different tax years.','Article worked calculation 3, simplified UK reporting-fund example. No tax rate is assumed. Retain relevant adjustments and historical ERI records.'),scenario=S('A relief election has a whole-return effect','Hypothetical foreign tax relieved: GBP 1,200.','Associated lost allowances create GBP 1,600 additional tax.','Net tax benefit is GBP −400: total tax is GBP 400 higher in this illustration.','Article worked calculation 2. These are assumed tax effects, not quoted tax rates or personal advice. Facts and eligibility must be established for the relevant year.'),action='Build a dated residence and fund-event calendar; retain units, distributions, ERI, cost, currency and disposal records.'),
'IIDF-03':dict(units=['Sender debit — total amount leaving the sender; GBP','Delivered amount — net recipient cash; KES','FX quote — offered KES per GBP, with time and expiry','Investable surplus — income after essentials, support and reserve funding'],calculation=F('Compare what the recipient actually receives','Recipient KES = (GBP budget − GBP fee) × KES/GBP − recipient charge','Route A: (500 − 5) × 165 = KES 81,675; Route B: 500 × 162 = KES 81,000','A zero transfer fee does not necessarily produce more recipient cash. Route A delivers KES 675 more.','Article worked calculation 3. Fictional simultaneous quotes; recipient charges assumed zero.'),scenario=S('The household budget comes before the broker transfer','GBP 3,000 − 1,800 essentials − 400 support − 300 reserve = GBP 500.','An additional GBP 250 essential expense arises.','Monthly investable surplus falls to GBP 250. Do not fund the unchanged contribution by quietly removing support or reserves.'),action='Save a same-time route comparison with total debit, recipient amount, eligibility, arrival time and quote expiry.'),
'KTHF-01':dict(units=['Gross cash pay — before cash deductions; KES/month','Taxable pay — income base after eligible deductions','Relief — reduction in assessed tax, not cash income','Take-home pay — cash remaining after actual payroll deductions'],calculation=F('A deduction and a cash payment do different jobs','Take-home pay = cash earnings − PAYE − cash deductions','Workbook taxable pay: January KES 126,305; February KES 124,145.','The KES 2,160 difference follows the scenario’s change in the employee NSSF deduction. Taxable pay is not take-home pay.','Payroll A4:H12. Dated 2026 teaching payroll. Keep the pension deduction convention and statutory periods from the source workbook.'),scenario=S('Compare months before annualising the payslip','January employee NSSF: KES 4,320.','February employee NSSF: KES 6,480.','The additional KES 2,160 cash deduction also changes the taxable-pay calculation; reconcile PAYE and net cash separately.'),action='Reconcile one payslip to bank cash, then assign dates to rent, essentials, debt and savings.'),
'KTHF-02':dict(units=['B — pension balance; KES','c — annual contribution; KES/year','r — net annual return after recurring fees','Real capital — nominal balance adjusted for cumulative inflation','Percentile — a conditional simulation outcome, not a guarantee'],calculation=F('Make contribution timing explicit','Bₜ = Bₜ₋₁ × (1 + rₜ) + cₜ','Source deterministic real capital: KES 10.662m; simulated median: KES 9.465m.','A deterministic scenario and a simulated median are different summaries and need not match.','Results A4:G15. Year-end contributions. Source simulation uses 1,000 hypothetical paths; target probability is conditional on the specified model.'),scenario=S('Read the range around the pension result','Median real capital: KES 9.465m.','Source 10th and 90th percentiles: KES 5.498m and KES 17.233m.','The range shows sensitivity to the modeled return paths. A higher recurring fee reduces retained capital across otherwise matched paths.','This slide compares simulated paths, not an observed probability distribution of future outcomes. Sampling error excludes model uncertainty.'),action='Record contribution timing, charges, target spending power and a review date; test contribution interruptions.'),
'KTHF-03':dict(units=['Deductible — eligible cost paid before private benefits apply','Co-payment — household share under policy terms','Limit — maximum covered payment for the stated claim period','Patient bill — gross bill less modeled insurer payments; KES'],calculation=F('Follow the actual claim waterfall','Patient bill = gross bill − public payment − private payment','KES 300,000 − KES 60,000 − KES 165,600 = KES 74,400','An insured household still needs accessible cash for its own payment and any income interruption.','Claims scenarios A4:H13. Fictional policy rules: do not treat modeled public/private payments as a coverage promise.'),scenario=S('The coverage limit changes the tail','Gross bill KES 1m; modeled patient bill KES 300,000.','Gross bill rises to KES 2m; private payment remains capped at KES 500,000.','Modeled patient bill rises to KES 1.1m. Add household spending during income interruption separately.'),action='Prepare a claims contact list and a reserve plan based on your policy’s exclusions, timing and limits.'),
'KTHF-04':dict(units=['Principal — unpaid loan balance; KES','Interest — period charge on outstanding principal','NPV — discounted difference between matched cash paths','Exit equity — sale proceeds less debt and exit costs'],calculation=F('The mortgage payment is only one housing cost','Principal repaid = scheduled payment − interest','Source loan: KES 4.8m; initial monthly payment: KES 56,235.63.','Entry cash is KES 1.44m before the emergency reserve; ownership also carries a modeled KES 5,000 monthly allowance.','Results A4:G15. Use the dated workbook assumptions, including timely payroll tax saving, rather than treating the figures as a current mortgage offer.'),scenario=S('Test a rate reset with the household budget','Source initial household surplus: KES 22,764.37/month.','Recalculate payment at a higher rate on the remaining balance and term.','Any extra payment reduces the surplus unless income or other spending changes; an optional prepayment follows a different mechanism.','Conceptual one-input rate test. The mortgage calculator is a separate default scenario; reconcile principal, rate, term and payment timing before comparing results.'),action='Build matched rent and buy cash schedules including entry, ongoing costs, loan balance and sale horizon.'),
'KECA-01':dict(units=['D — dividend per share; KES/share','P — purchase price; KES/share','t — withholding rate; decimal','c — acquisition cost rate; decimal','Outlay — actual cash paid, including costs'],calculation=F('Compare income on the cash actually paid','Net dividend yield = D(1 − t) ÷ [P(1 + c)]','91-day bill: face KES 100,000; clean price KES 97,860.60; tax at purchase KES 320.91.','The bill’s settlement outlay includes purchase tax; compare its maturity gain over the same investment period.','Bill pricing A4:F16. Dated accepted annual yield 8.7687% is a historical source input; not a new offer.'),scenario=S('A dividend cut changes income without reducing your original outlay','Hold purchase price and acquisition cost fixed.','Reduce the assumed recurring dividend by 20%.','Net dividend cash and yield on that unchanged outlay fall by 20%; a special dividend should not be carried forward automatically.','Illustrative sensitivity, not a forecast for any named issuer.'),action='Record ordinary and special distributions separately, then compare net cash with Treasury-bill settlement and maturity dates.'),
'KECA-02':dict(units=['FCFF — free cash flow to the firm before debt payments','WACC — discount rate matching the enterprise cash flows','g — sustainable terminal growth; must be below WACC','ROIC — return on incremental invested capital','Equity bridge — enterprise value adjusted for cash, debt and other claims'],calculation=F('Terminal growth requires reinvestment','Terminal FCFF = terminal NOPAT × (1 − g/ROIC)','Source terminal NOPAT 1,626.33 × (1 − 25%) = 1,219.75.','The model then discounts forecast and terminal cash flows; source enterprise value is 9,693.04 in its stated model units.','DCF A4:H14. The source workbook model, the BAT filed facts and the web DCF defaults are three distinct cases.'),scenario=S('Raise the required return; preserve the forecast','Use the source five-year cash-flow forecast.','Increase WACC by one percentage point; hold those five cash flows fixed.','Their present value falls. Terminal value also changes through the WACC-minus-growth denominator and discount factor.','Do not use industrial FCFF for banks or insurers; use the appropriate equity/capital model. No new issuer value is asserted.'),action='Write a value range with cash-flow, reinvestment, growth and discount-rate assumptions; identify the missing source evidence.'),
'KECA-03':dict(units=['Weight — fraction of portfolio value','Covariance — joint return variability','Risk contribution — weight × covariance with the portfolio','Whole-share quantity — integer units affordable after costs'],calculation=F('Capital weight and risk contribution can diverge','Variance contributionᵢ = weightᵢ × Cov(returnᵢ, portfolio return)','Balanced SCOM: 15% × 0.030600 = 0.004590; 24.98% of modeled portfolio variance.','A 15% capital weight can contribute almost 25% of modeled variance because dependence matters.','Risk contributions A4:G13. Historical/assumed covariance model in the source is not a forecast guarantee.'),scenario=S('Read shared bank exposure across positions','EQTY, KCB and COOP each carry a 10% balanced weight.','Inspect their combined modeled variance contributions.','15.19% + 17.08% + 12.75% = 45.02% of portfolio variance for 30% of capital in this model.','Source risk-contribution snapshot. This aggregation does not establish the cause of future risk or a stable expected contribution.'),action='Translate the allocation into affordable whole-share orders and record concentration, liquidity and review limits.'),
'KECA-04':dict(units=['Nominal wealth — amount in future currency units','Real wealth — amount in today’s purchasing power','Price index — cumulative inflation multiplier','Simulation — conditional paths generated by stated assumptions'],calculation=F('Translate nominal wealth into purchasing power','Real wealth = nominal wealth ÷ cumulative price index','Year 1 median: KES 1,197,979.16 ÷ 1.05 = KES 1,140,932.54.','Nominal growth is only part of progress toward a spending goal.','Simulation summary A4:G14. Source illustrative inflation 5% for the displayed first-year relationship.'),scenario=S('Keep nominal cash; change the purchasing-power assumption','Same nominal balance and horizon.','Increase the assumed cumulative inflation factor.','Real purchasing power falls; higher contributions can offset some loss but require household cash today.'),action='Review contributions, inflation, spending needs and drawdowns together; preserve the simulation assumptions and random-path context.'),
}
# The nine US episodes and NSE/leadership use their own topic selections rather than the older storyboard's recurring headings.
EXTRA={
'NSE-DG-01':(['Stage KES 100,000 over three months','Retain cash for acquisition costs and whole-share rounding.','A core is a portfolio role with a review rule, not a universal ticker list.','Treat dividend sustainability and total return as related but distinct questions.'],['A whole-share order leaves residual cash','Use the saved reference price and its date.','Monthly allocation is rounded down to an affordable integer quantity.','Record both share cost and maximum modeled fees.'],['Trace the dividend into net household cash','Separate ordinary distributions from special payments.','Apply the relevant withholding assumptions explicitly.','Review payout, cash generation, debt and reinvestment before extrapolating income.']),
'NSE-DG-02':(['A watchlist is a research queue','Record why each candidate could fill a portfolio role.','A candidate may remain deferred while evidence is missing.','A new ticker does not automatically add a new economic exposure.'],['Compare the candidate with what you already own','Aggregate banks, sectors and shared operating drivers.','Include liquidity, cash needs and maximum position size.','Look through overlapping holdings before calling the portfolio diversified.'],['Make entry discipline inspectable','Record the price date, valuation range and source.','Set required evidence and the condition that rules out a purchase.','Review quarterly and after a material change; expire stale theses.']),
'USMPC-01':(['Start with the economic claim','A company operates a business; a security defines an investor claim.','An exchange is a trading venue, while an index is a rule-based measurement.','A fund holds assets under a mandate; a portfolio combines claims for a purpose.'],['Benchmarks answer different questions','A large-company benchmark differs from a broad market or growth-heavy benchmark.','Weighting rules affect whose returns dominate the result.','Compare total return, currency and time period on a consistent basis.'],['Risk has more than one dimension','Volatility measures variability, while a drawdown describes a peak-to-trough loss.','Liquidity affects whether an investor can transact at a useful price.','Match horizon, spending currency and acceptable loss before selecting a wrapper.']),
'USMPC-02':(['A wrapper changes implementation','Direct shares, mutual funds and ETFs package ownership differently.','Creation and redemption connect ETF shares with the underlying basket.','Legal structure, dealing mechanics and investor eligibility belong in the comparison.'],['Count four layers of cost','The fund expense ratio compounds inside the investment.','Spread, commissions and market impact affect execution.','Tax, currency conversion and funding affect what the household retains.'],['Make the fee comparison comparable','Keep the gross return, horizon and contributions the same.','Date each published fee and benchmark description.','Different exposures cannot be ranked solely by expense ratio.']),
'USMPC-03':(['Begin with the investor’s facts','Record residence, citizenship, account owner and relevant treaty position.','Separate the legal domicile from the exchange and dealing currency.','Trace the dividend from company through fund to investor.'],['Separate withholding from estate exposure','A payment-tax assumption does not resolve an ownership-at-death question.','Retain account, security and beneficiary records.','Use dated rules and investor-specific eligibility before implementing a route.'],['Currency belongs in the same record','Fund denomination and trading currency do not define every underlying exposure.','Match near-term cash obligations to their spending currency.','Compare custody, funding, reporting and exit costs as one implementation path.']),
'USMPC-04':(['Define jobs before tickers','A strategic core carries the enduring policy exposure.','A satellite takes a limited, explicit active risk.','Every sleeve needs a target, loss budget and decision authority.'],['Diversification depends on joint movement','Mixing equity and bonds changes both volatility and expected behaviour.','Portfolio standard deviation is not a weighted average of individual volatilities.','Correlation assumptions need a stress test when regimes change.'],['Architecture should constrain behaviour','Core-satellite, factor tilts and barbell designs make different commitments.','A concentrated sleeve needs a credible maximum-loss budget.','Choose a policy that the investor can fund, explain and maintain.']),
'USMPC-05':(['The benchmark comes before the ticker','SPYM provides S&P 500 exposure in the source comparison.','QQQM adds a deliberate Nasdaq-100 growth tilt.','A second fund may increase exposure to companies already held.'],['Look through the labels','Multiply fund weights by each underlying company weight.','Aggregate shared companies before assessing concentration.','Use HHI and effective holding count as diagnostics, not complete risk measures.'],['Contributions can repair drift','Send new cash to underweight sleeves before assuming a sale is needed.','Track spreads and liquidity alongside published fund fees.','Document the intended tilt and a maximum active weight.']),
'USMPC-06':(['Semiconductors are a concentrated industry exposure','SOXQ, SOXX, SMH and XSD use different eligibility and weighting rules.','Foundry, design, equipment and memory businesses have different drivers.','A low expense ratio does not remove cyclical or geopolitical risk.'],['The satellite overlaps the core','Aggregate company exposures across broad and thematic funds.','Weight concentration changes the impact of a single-company loss.','Test the semiconductor sleeve with growth and market exposures together.'],['Choose a loss budget before a theme','Size the sleeve using a plausible stress loss.','Set a target band and a thesis-break condition.','Record the evidence that would reduce, retain or exit the position.']),
'USMPC-07':(['A premium pays for an obligation','A cash-secured put may require buying the underlying at the strike.','A covered call limits upside while retaining downside ownership risk.','The underlying must be suitable even if assignment occurs.'],['Contract size creates concentration','One standard contract represents 100 shares in the source example.','Cash collateral is committed capital, not freely available reserve.','A small premium cannot offset an arbitrarily large underlying loss.'],['Evaluate the complete cycle','Include premiums, underlying price change, costs and taxes.','Do not annualise one favourable cycle as an expected return.','Benchmark the strategy against a consistent underlying and cash alternative.']),
'USMPC-08':(['Integrate all sleeves into one policy','The illustrative allocation combines core equity, bonds, a growth tilt and a satellite.','Look-through holdings reveal overlap hidden by the four labels.','Options collateral and cash reserves share the same balance sheet.'],['Risk contributions need a joint model','Volatility and correlations turn weights into portfolio variability.','A small volatile sleeve can contribute a larger share of risk.','Use scenario tables and review model assumptions before optimisation.'],['Rebalancing is a rule, not a prediction','Choose calendar, threshold or contribution-first triggers.','Calculate target trades using current total value.','Document costs, taxes, liquidity and the person authorised to trade.']),
'USMPC-09':(['Funding has its own timing decision','Lump-sum investment and staged contributions expose cash at different dates.','Keep the total amount and comparison horizon consistent.','The useful choice depends on cash needs, risk capacity and implementation.'],['Withdrawals make return order matter','The same set of annual returns can produce different ending balances.','Early losses plus withdrawals leave fewer assets to recover.','Test reserves, flexible spending and rebalancing together.'],['Maintenance is a household process','Revisit income, contributions, beneficiaries and near-term spending.','Separate documented policy changes from reactions to recent performance.','Preserve a review calendar and a decision record.']),
'LEAD-01':(['Map the dependency, not the personality','List decisions, customer relationships and operating knowledge held by one person.','Identify which work stops if the founder is unavailable.','Prioritise dependencies by time to disruption and business consequence.'],['Authority and access need separate controls','A deputy needs authority to act, not merely a password.','Preserve approvals, access recovery and legal signing arrangements.','Test handovers through real work with documented escalation.'],['Make continuity measurable','Build customer relationships beyond a single individual.','Use a short continuity plan with named deputies and contact routes.','Review performance through a ninety-day resilience programme.'])}
extra_metrics={
'NSE-DG-01':('Whole-share implementation','Shares = floor(monthly capital allocation ÷ reference price)','Safaricom: floor(KES 6,529.55 ÷ KES 36.65) = 178 shares.','Source share cost KES 6,523.70; cost plus maximum modeled fees KES 6,660.70.'),
'NSE-DG-02':('Read the current core before adding a candidate','Combined sector weight = sum of constituent position weights','Equity 15% + Co-operative Bank 15% + Standard Chartered Kenya 15% = 45%.','Three separate holdings still leave 45% of the illustrative target in banks.'),
'USMPC-01':('A return changes a starting claim','Ending value = beginning value × (1 + total return)','Teaching input: USD 10,000 × 1.08 = USD 10,800.','An 8% illustrative total return says nothing by itself about the next period or the investor’s spending-currency return.'),
'USMPC-02':('A recurring fee compounds','FV = P × (1 + r − e)ⁿ','USD 10,000 at 8% gross less 0.020% annual fee → USD 100,069.03 after 30 years.','Under the same gross-return assumption, the source 0.750% fee case ends at USD 81,643.01.'),
'USMPC-03':('Trace the withholding cash flow','Net dividend = position × dividend yield × (1 − withholding rate)','USD 10,000 × 1.3% × (1 − 30%) = USD 91.00.','At an illustrative eligible 15% rate, net cash is USD 110.50: a USD 19.50 difference before other costs.'),
'USMPC-04':('Joint risk is not a weighted-average volatility','σₚ² = w₁²σ₁² + w₂²σ₂² + 2w₁w₂σ₁σ₂ρ','70% equity / 30% bonds; 16% / 6% volatility; correlation 0.10 → portfolio σ 11.52%.','The naive linear average is 13.00%; covariance explains the difference.'),
'USMPC-05':('Concentration has an effective count','HHI = Σwᵢ²; effective N = 1/HHI','30 equal weights: HHI = 0.03333; effective N = 30.','Unequal weights reduce the effective count even if the nominal holding count is unchanged.'),
'USMPC-06':('Size the satellite against a stress loss','Portfolio loss contribution ≈ sleeve weight × sleeve loss','Illustration: 15% sleeve × −40% sleeve return = −6 percentage points.','Other sleeves can fall at the same time. This isolates one contribution, not the full stress outcome.'),
'USMPC-07':('The put premium does not remove downside','Put payoff per share = premium − max(strike − ending price, 0)','Strike USD 90; premium USD 2; one contract → collateral USD 9,000 and premium USD 200.','Assigned break-even is USD 88/share before fees and tax; the short put retains substantial downside.'),
'USMPC-08':('Calculate the trade from the current total','Tradeᵢ = target weightᵢ × current portfolio value − current sleeve valueᵢ','Source SPYM: target USD 32,532.50 − current USD 31,625.00 = buy USD 907.50.','The four source rebalance trades net to zero before transaction costs.'),
'USMPC-09':('Withdrawals change the sequence outcome','Closing balance = opening balance × (1 + return) − withdrawal','USD 1m with bad years first ends at USD 666,446; the reordered path ends at USD 895,643.','The source uses the same returns with USD 45,000 withdrawn annually at year end.'),
'LEAD-01':('Make the response time visible','Continuity gap = time to restore a critical function − tolerable interruption','Record each function’s tolerable interruption, deputy and tested recovery time.','An untested deputy or inaccessible authorisation leaves a gap even if the plan looks complete.')}
extra_scenarios={
'NSE-DG-01':S('Price changes alter the affordable quantity','Keep the monthly allocation and fee budget fixed.','Increase the observed share price before executing the order.','Recalculate whole shares and residual cash; do not force the original quantity through the cash limit.'),
'NSE-DG-02':S('The new bank candidate may deepen an existing tilt','The example core already targets 45% in three banks.','Consider another bank without reducing existing bank holdings.','Sector exposure rises; compare its incremental role and risk before adding a position.'),
'USMPC-01':S('A drawdown needs a larger percentage recovery','Teaching balance falls from USD 10,000 to USD 8,000: −20%.','Recover from USD 8,000 to the original USD 10,000.','Required return is 10,000/8,000 − 1 = 25%, before withdrawals or costs.'),
'USMPC-02':S('Keep the exposure assumption; change only the fee','Source 30-year ending value at 0.020% fee: USD 100,069.03.','Source active-fund illustration at 0.750% fee: USD 81,643.01.','Fee-only gap is USD 18,426.02. This holds gross returns equal and is not a performance forecast.'),
'USMPC-03':S('Treaty eligibility changes the payment assumption','No-treaty illustration: 30% withholding on USD 130.','Eligible illustrative treaty treatment: 15% on the same USD 130.','Tax withheld falls from USD 39 to USD 19.50. Actual eligibility must be documented.'),
'USMPC-04':S('A concentrated sleeve spends the loss budget','Teaching sleeve weight 10%; assumed loss 50%.','Raise the sleeve weight to 20% with the same 50% loss.','Its portfolio loss contribution doubles from 5 to 10 percentage points, before other positions move.'),
'USMPC-05':S('An equal nominal count can mask different concentration','Thirty equally weighted holdings have effective N of 30.','Increase a few weights and reduce the rest while retaining 30 names.','HHI increases and effective N falls. Inspect common holdings across funds before interpreting the fund count.'),
'USMPC-06':S('Test the satellite without promising a loss limit','15% satellite; illustrative −40% sleeve shock.','Increase the weight to 20%, retaining the same shock.','Loss contribution rises from −6 to −8 percentage points; correlations can add wider portfolio losses.'),
'USMPC-07':S('Assignment can overwhelm the collected premium','The USD 90 put collects USD 2/share.','The underlying ends at USD 70.','Payoff = 2 − (90 − 70) = USD −18/share, or USD −1,800 for one contract, before costs.'),
'USMPC-08':S('Use new contributions before assuming a sale','Current weights drift away from the four-sleeve targets.','Direct new cash toward underweight sleeves first.','Recalculate residual trades on the new portfolio total; compare taxes and costs before selling.'),
'USMPC-09':S('Return order matters after spending begins','Bad years first: ending wealth USD 666,446.24.','Same returns reordered; bad years last: USD 895,643.36.','The difference is USD 229,197.12 under the source withdrawal schedule, despite the same set of returns.'),
'LEAD-01':S('Test an absence before it becomes a crisis','Founder approves payments, handles a key customer and holds critical knowledge.','Run a planned absence with a named deputy and documented limits.','Record blocked decisions and delays; revise authority, training and customer ownership before repeating the test.')}
for id,triples in EXTRA.items():
 D[id]=dict(beats=[B(*x) for x in triples],calculation=F(*extra_metrics[id]),scenario=extra_scenarios[id],units={
 'NSE-DG-01':['DCA — investing fixed contributions at scheduled dates','Whole shares — integer quantity affordable within cash limits','Residual cash — unspent amount after share purchases and costs'],
 'NSE-DG-02':['Target weight — desired proportion of the portfolio','Concentration — exposure clustered in related claims','Watchlist — research candidates with an evidence status'],
 'LEAD-01':['Critical function — activity whose interruption causes material harm','Deputy — named person trained and authorised to act','Recovery time — tested time needed to resume the function']}.get(id,['P, FV — starting and future portfolio value; USD','w — portfolio weight; decimal or stated percentage','r — return for the stated period; decimal','Source market facts are dated; numerical stress inputs are illustrations']),action={
 'USMPC-01':'Write purpose, spending currency, time horizon and acceptable loss before choosing a fund.',
 'USMPC-02':'Record eligible wrappers and the full cost path, including funding, execution, tax and exit.',
 'USMPC-03':'Complete an investor-to-fund implementation record with documented eligibility and source dates.',
 'USMPC-04':'Choose an architecture and write each sleeve’s purpose, target, loss budget and review authority.',
 'USMPC-05':'Document the core, intended tilt, look-through exposure and maximum active weight.',
 'USMPC-06':'Set a satellite target, band and thesis-break condition tied to named evidence.',
 'USMPC-07':'Define eligible underlyings, collateral reserve and the response to a loss-and-assignment scenario.',
 'USMPC-08':'Adopt review dates, drift triggers and a contribution-first rule in one investment policy.',
 'USMPC-09':'Add near-term spending, reserve sequencing and withdrawal review dates to the portfolio policy.',
 'NSE-DG-01':'Save the purchase log with capital budget, source price date, fees, integer shares and review trigger.',
 'NSE-DG-02':'Add a candidate with source links, a valuation range, an exposure role and pass/revise/defer status.',
 'LEAD-01':'Create a dependency map, named deputies and a ninety-day programme of tested handovers.'}[id])
answers={
'AMBC-01':'Trade activity attracts capital, but useful investment must improve reliability, financing and customer service. Ownership changes, new funding and operating cash benefits occur through different routes and at different stages.',
'AMBC-02':'Credit helps when total cost and repayment dates fit a verified operating cycle. Clear borrower records, collection evidence and disciplined follow-up matter alongside the lender’s ownership and funding.',
'IIDF-01':'An ETF combines exposure, domicile, share class, trading currency and exchange. A structure improves the investor’s outcome only when its relevant tax and recurring-cost advantages exceed its implementation costs.',
'IIDF-02':'Residence and transaction dates determine which income, gains, accounts and reporting rules must be examined. Preserve records across the move and fund tax obligations separately from family support and investing.',
'IIDF-03':'A usable payment route requires eligible accounts, supported currencies and a workable recipient channel. Compare delivered cash, then give support, reserves and investment contributions their own amounts and dates.',
'KTHF-01':'Spendable cash follows actual payroll and household payments, not taxable pay alone. Dated payslips and cash commitments make the monthly plan testable when deductions, income or policy change.',
'KTHF-02':'Contributions, timing, fees, inflation and return paths shape retirement purchasing power. Conditional scenarios reveal sensitivity; current liquidity and a later withdrawal plan remain separate decisions.',
'KTHF-03':'Insurance covers defined claims under its terms. Accessible reserves fund household payments, timing gaps and lost income; the policy and the cash plan must be read together.',
'KTHF-04':'A useful housing comparison includes entry cash, loan payments, maintenance, exit debt and the same rental horizon. Stress the full household budget when rates or income change.',
'KECA-01':'Compare net distributions or maturity gains with the cash actually paid, using consistent periods. Cash generation, reinvestment and sector capital needs determine whether distributions can continue.',
'KECA-02':'A defensible value range makes cash generation, reinvestment, growth and required returns explicit. Sector-specific claims and sensitivity analysis explain what can change the estimate.',
'KECA-03':'Weights, shared exposures and concentration shape portfolio risk. Whole-share quantities, costs and liquidity then connect the allocation policy to an affordable order plan.',
'KECA-04':'Contributions, inflation and return order affect purchasing power and goal attainment. A conditional simulation helps compare choices; it does not promise a future outcome.',
'USMPC-01':'The economic claim, benchmark and ownership vehicle answer different questions. Define the investor’s job for the money before combining them into a portfolio.',
'USMPC-02':'What the investor retains depends on recurring costs, execution, tax and funding together. A low stated fee helps only within an exposure and ownership structure that fits the investor.',
'USMPC-03':'The same underlying exposure can produce different outcomes through residence, domicile, withholding, custody and currency. Preserve the investor’s dated facts and document the entire route.',
'USMPC-04':'A portfolio architecture assigns jobs and limits to each sleeve. It becomes useful when risk budgets, funding and governance constrain later security choices.',
'USMPC-05':'A broad core and a growth fund can form a deliberate tilt rather than independent diversification. Look-through weights and a review rule make that intention visible.',
'USMPC-06':'A thematic fund adds concentrated industry risk even when it holds multiple companies. Size the position against a portfolio loss budget and explicit thesis conditions.',
'USMPC-07':'Option premium is compensation for an obligation. A tactical sleeve needs suitable underlying ownership, sufficient collateral and a complete downside-and-assignment plan.',
'USMPC-08':'Separate sleeves form one policy only when overlap, covariance, collateral, costs and rebalancing are considered together. A governance rule makes the portfolio maintainable.',
'USMPC-09':'Contribution and withdrawal timing connect investments to the household. Sequence tests, accessible reserves and scheduled reviews help keep the portfolio useful when life changes.',
'NSE-DG-01':'A staged contribution plan must fit fees, whole-share quantities and residual cash. Dividend assessment then asks whether the underlying business can sustain the payment.',
'NSE-DG-02':'A watchlist broadens research when each candidate has an evidence requirement and a portfolio role. A deferred decision can be the correct output.',
'LEAD-01':'Key-person risk is concentration of knowledge, relationships and authority. Resilience improves when deputies perform real work and the continuity plan is tested.'}
result=[]
for a in src['articles']:
 if a['id'] not in D: continue
 d=D[a['id']]; series=next(s for s in src['series'] if s['id']==a['series_id'])
 d.update(id=a['id'],case=series.get('case') or a['summary'] if 'summary' in a else series.get('case','The article’s dated investor decision.'),caseLabel='Dated source record • fictional calculations are labelled as illustrations')
 if 'beats' not in d:
  rows=[x for x in a['storyboard'] if 4<=int(x['Slide'])<=9]
  d['beats']=[B(rows[i]['Title']+' / '+rows[i+1]['Title'],rows[i]['Visible content'],rows[i+1]['Visible content']) for i in (0,2,4)]
 if a['id'] in answers:d['answer']=answers[a['id']]
 else:d['answer']=next((x['Visible content'] for x in a['storyboard'] if int(x['Slide'])==13),'The evidence answers the opening decision under its stated assumptions.')
 if a['id'].startswith('USMPC'):d['case']='An educational US-market portfolio, funded and maintained through an explicit policy rather than a prediction of the next winning fund.'
 if a['id']=='NSE-DG-01':d['case']='A dated KES 100,000 teaching allocation staged through three monthly purchases with fees and whole-share constraints.'
 if a['id']=='NSE-DG-02':d['case']='An investor compares new research candidates with an existing Kenyan equity core, preserving the option to defer.'
 if a['id']=='LEAD-01':d['case']='A founder-led business rehearses who can serve customers, approve payments and recover critical records if the founder is unavailable.'
 if a['id'].startswith('USMPC'):
  d['units']={
   'USMPC-01':['Total return — price change plus distributions; stated reinvestment basis','Benchmark — rule-defined market measurement','Drawdown — loss from a prior peak; %','Liquidity — ability to transact at a usable price'],
   'USMPC-02':['P — initial principal; USD','r — assumed gross annual return; decimal','e — recurring annual expense ratio; decimal','n — investment horizon; years','FV — ending value before excluded tax/transaction costs; USD'],
   'USMPC-03':['Position — market value used in the example; USD','Yield — annual gross dividend ÷ position value','Withholding — tax deducted from the distribution; %','Domicile — legal jurisdiction of the fund','Treaty eligibility — investor-specific entitlement requiring evidence'],
   'USMPC-04':['w — portfolio capital weight; decimal','σ — annualised standard deviation; decimal','ρ — correlation between the two return series','Variance — squared standard deviation','Loss budget — acceptable portfolio impact of the stress'],
   'USMPC-05':['wᵢ — look-through weight of company i','HHI — sum of squared company weights','Effective N — 1/HHI; equally weighted equivalent count','Active weight — exposure above or below the benchmark'],
   'USMPC-06':['Satellite weight — fraction of total portfolio capital','Stress return — assumed sleeve return in the scenario','Loss contribution — weight × stress return','Percentage point — additive impact on portfolio return','Thesis break — evidence that invalidates the sleeve rationale'],
   'USMPC-07':['Strike — contracted exercise price; USD/share','Premium — cash received for the option; USD/share','Contract — 100 shares in this teaching example','Collateral — cash committed to the potential purchase','Payoff — result at expiration before fees and tax'],
   'USMPC-08':['Target weight — policy allocation; decimal','Current value — marked sleeve value; USD','Target value — weight × total portfolio value; USD','Trade — target value less current value; USD','Drift — deviation of actual weight from the target'],
   'USMPC-09':['Withdrawal — cash removed at the stated date; USD','Sequence risk — effect of return order with investor cash flows','Real wealth — nominal wealth adjusted for inflation','Reserve — accessible money for near-term spending']
  }[a['id']]
 result.append(d)
(A/'content/existing-episodes.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'Curated {len(result)} existing episodes.')
